Removing the use of functions
aserto-dev/policy-peoplefinder-rbac pull request #1
Opened 2021-11-02 15:51 UTC by squanchd

2021-11-02 17:15 UTC, authereal commented
@ogazitt do we want the policy file naming convention to be `<package name>.rego`?

2021-11-02 20:09 UTC, authereal commented
can we remove the `"peoplefinder.IMPERSONATE.api.users.__id"` sections in `roles/data.json`? looks like the policy was already removed: https://github.com/aserto-demo/policy-peoplefinder/commit/f7fbeb51e4085351168322b3108249c617343f3e

2021-11-08 20:04 UTC, ogazitt requested changes

2021-11-08 20:04 UTC, ogazitt commented on src/roles/data.json
> -        "viewer": {
I'm not sure why this file changed?

2021-11-08 20:04 UTC, ogazitt commented on src/policies/__id/peoplefinder.DELETE.api.users.__id.rego
> +import input.user.applications.peoplefinder
we're no longer using input.user.applications.peoplefinder - we should be using input.user.attributes

2021-11-08 20:04 UTC, ogazitt commented on src/policies/__id/peoplefinder.DELETE.api.users.__id.rego
> +package peoplefinder.DELETE.api.users.__id
renaming all the files is a convention change - I'm not against it per se, but it should be done as a joint decision. adding @gertd for his opinion.

2021-11-08 20:10 UTC, squanchd commented on src/roles/data.json
> -        "viewer": {
I removed the "Impersonate" entries.

2021-11-09 01:19 UTC, ogazitt commented on src/roles/data.json
> -        "viewer": {
👍

2021-11-11 17:45 UTC, ogazitt approved these changes

2021-11-11 17:45 UTC, merged